// Mock manifest matching Path 2 (adaptation run) from the ADK spec
export const MOCK_MANIFEST = {
  manifest_version: '1.1',
  pipeline_run_id: 'run_9a2b3c4d',
  market: 'Korea',
  market_nationality: 'Korean',
  campaign_name: 'Korea Summer 2026',
  total_reference_images: 5,
  total_jobs: 34,
  total_text_items: 12,
  reference_images: [
    {
      ref_id: 'ref_aud01_cat',
      subject_label: 'Fluffy Pet Cat',
      prompt: 'Small domestic cat, light ginger & white fur, tabby markings, bright green eyes. Photorealistic style, soft lighting, warm tones.',
      negative_prompt: 'cartoon, illustration, dark, scary, aggressive',
      model: 'gemini-3-pro-image-preview',
      style: { resolution: '1024x1024' },
      output_path: 'Female 18-24/references/ref_aud01_cat.png',
      priority: 0,
      audience_id: 'aud_01',
      audience_name: 'Female 18-24',
    },
    {
      ref_id: 'ref_aud01_landscape',
      subject_label: 'Serene Mountain Landscape',
      prompt: 'Snow-capped peaks, lush valleys, clear sky — grand sweeping view. Cinematic landscape photography, golden hour lighting.',
      negative_prompt: 'urban, buildings, people, text, watermark',
      model: 'gemini-3-pro-image-preview',
      style: { resolution: '1024x1024' },
      output_path: 'Female 18-24/references/ref_aud01_landscape.png',
      priority: 0,
      audience_id: 'aud_01',
      audience_name: 'Female 18-24',
    },
    {
      ref_id: 'ref_aud03_pixel_character',
      subject_label: 'Retro Pixel Art Character',
      prompt: '8-bit arcade hero, blocky outline, bold colors, classic gaming style. Pixel art, retro aesthetic.',
      negative_prompt: 'realistic, photographic, 3D render, smooth',
      model: 'gemini-3-pro-image-preview',
      style: { resolution: '1024x1024' },
      output_path: 'Male 18-24/references/ref_aud03_pixel_character.png',
      priority: 0,
      audience_id: 'aud_03',
      audience_name: 'Male 18-24',
    },
    {
      ref_id: 'ref_aud03_neon_car',
      subject_label: 'Futuristic Neon Race Car',
      prompt: 'Sleek low-profile car, glowing neon underlights, cyberpunk aesthetic. Dark background, dramatic lighting.',
      negative_prompt: 'vintage, rusty, broken, daytime, realistic traffic',
      model: 'gemini-3-pro-image-preview',
      style: { resolution: '1024x1024' },
      output_path: 'Male 18-24/references/ref_aud03_neon_car.png',
      priority: 0,
      audience_id: 'aud_03',
      audience_name: 'Male 18-24',
    },
    {
      ref_id: 'ref_aud04_motorcycle',
      subject_label: 'Vintage Cafe Racer Motorcycle',
      prompt: 'Classic cafe racer, dark metallic paint, brown leather seat. Studio photography, clean background.',
      negative_prompt: 'modern, sportbike, dirt, damaged, cartoon',
      model: 'gemini-3-pro-image-preview',
      style: { resolution: '1024x1024' },
      output_path: 'Male 25-34/references/ref_aud04_motorcycle.png',
      priority: 0,
      audience_id: 'aud_04',
      audience_name: 'Male 25-34',
    },
  ],
  jobs: [
    {
      job_id: 'job_001',
      scene: 'scene_01',
      element: 'nested_01',
      asset_type: 'image',
      prompt: 'A young Korean woman gently holding a fluffy ginger cat, cozy apartment, warm afternoon light streaming through window.',
      negative_prompt: 'dark, scary, outdoor, cold tones',
      model: 'gemini-3-pro-image-preview',
      style: { aspect_ratio: '9:16' },
      ref_dependencies: ['ref_aud01_cat'],
      output_path: 'Female 18-24/scene_01/nested_01.png',
      priority: 1,
      audience_id: 'aud_01',
      audience_name: 'Female 18-24',
    },
    {
      job_id: 'job_002',
      scene: 'scene_01',
      element: 'nested_02',
      asset_type: 'image',
      prompt: 'Close-up of the fluffy ginger cat curled up on a soft blanket, eyes half-closed, content expression.',
      negative_prompt: 'alert, standing, outdoor, harsh light',
      model: 'gemini-3-pro-image-preview',
      style: { aspect_ratio: '9:16' },
      ref_dependencies: ['ref_aud01_cat'],
      output_path: 'Female 18-24/scene_01/nested_02.png',
      priority: 1,
      audience_id: 'aud_01',
      audience_name: 'Female 18-24',
    },
    {
      job_id: 'job_003',
      scene: 'scene_03',
      element: 'hero_shot',
      asset_type: 'video',
      prompt: 'Sweeping drone shot over snow-capped mountain peaks, camera slowly descending into lush green valley. Epic cinematic style.',
      negative_prompt: 'handheld, shaky, urban, text overlay',
      model: 'veo-3.1-generate-preview',
      style: { aspect_ratio: '9:16', duration_seconds: 6 },
      ref_dependencies: ['ref_aud01_landscape'],
      output_path: 'Female 18-24/scene_03/generated_video.mp4',
      priority: 1,
      audience_id: 'aud_01',
      audience_name: 'Female 18-24',
    },
    {
      job_id: 'job_004',
      scene: 'scene_01',
      element: 'hero_shot',
      asset_type: 'image',
      prompt: 'Retro pixel art character standing in a neon-lit arcade, holding a joystick, determined expression. 8-bit style.',
      negative_prompt: 'realistic, 3D, smooth shading, photographic',
      model: 'gemini-3-pro-image-preview',
      style: { aspect_ratio: '9:16' },
      ref_dependencies: ['ref_aud03_pixel_character'],
      output_path: 'Male 18-24/scene_01/hero_shot.png',
      priority: 1,
      audience_id: 'aud_03',
      audience_name: 'Male 18-24',
    },
    {
      job_id: 'job_005',
      scene: 'scene_02',
      element: 'action_shot',
      asset_type: 'image',
      prompt: 'Futuristic neon race car drifting around a corner, sparks flying, rain-slicked cyberpunk city street.',
      negative_prompt: 'daytime, vintage, countryside, cartoon',
      model: 'gemini-3-pro-image-preview',
      style: { aspect_ratio: '9:16' },
      ref_dependencies: ['ref_aud03_neon_car'],
      output_path: 'Male 18-24/scene_02/action_shot.png',
      priority: 1,
      audience_id: 'aud_03',
      audience_name: 'Male 18-24',
    },
    {
      job_id: 'job_006',
      scene: 'scene_03',
      element: 'hero_video',
      asset_type: 'video',
      prompt: 'Neon race car accelerating down a futuristic highway, camera tracking alongside. Cyberpunk city lights blur in background.',
      negative_prompt: 'slow, parked, daytime, realistic traffic',
      model: 'veo-3.1-generate-preview',
      style: { aspect_ratio: '9:16', duration_seconds: 6 },
      ref_dependencies: ['ref_aud03_neon_car'],
      output_path: 'Male 18-24/scene_03/generated_video.mp4',
      priority: 1,
      audience_id: 'aud_03',
      audience_name: 'Male 18-24',
    },
    {
      job_id: 'job_007',
      scene: 'scene_01',
      element: 'hero_shot',
      asset_type: 'image',
      prompt: 'Vintage cafe racer motorcycle parked outside a Korean coffee shop, morning golden hour, steam rising from a cup nearby.',
      negative_prompt: 'modern sportbike, night, rain, dirty, damaged',
      model: 'gemini-3-pro-image-preview',
      style: { aspect_ratio: '9:16' },
      ref_dependencies: ['ref_aud04_motorcycle'],
      output_path: 'Male 25-34/scene_01/hero_shot.png',
      priority: 1,
      audience_id: 'aud_04',
      audience_name: 'Male 25-34',
    },
    {
      job_id: 'job_008',
      scene: 'scene_02',
      element: 'detail_shot',
      asset_type: 'image',
      prompt: 'Close-up of vintage cafe racer chrome details, leather seat texture, warm tones. Product photography style.',
      negative_prompt: 'wide shot, people, text, cartoon, damaged',
      model: 'gemini-3-pro-image-preview',
      style: { aspect_ratio: '9:16' },
      ref_dependencies: ['ref_aud04_motorcycle'],
      output_path: 'Male 25-34/scene_02/detail_shot.png',
      priority: 1,
      audience_id: 'aud_04',
      audience_name: 'Male 25-34',
    },
    {
      job_id: 'job_009',
      scene: 'scene_03',
      element: 'hero_video',
      asset_type: 'video',
      prompt: 'Vintage cafe racer motorcycle cruising along a scenic Korean coastal road, sunset in background. Cinematic tracking shot.',
      negative_prompt: 'highway, traffic, urban, rain, night',
      model: 'veo-3.1-generate-preview',
      style: { aspect_ratio: '9:16', duration_seconds: 6 },
      ref_dependencies: ['ref_aud04_motorcycle'],
      output_path: 'Male 25-34/scene_03/generated_video.mp4',
      priority: 1,
      audience_id: 'aud_04',
      audience_name: 'Male 25-34',
    },
    {
      job_id: 'job_010',
      scene: 'scene_02',
      element: 'lifestyle_shot',
      asset_type: 'image',
      prompt: 'Korean woman hiking through mountain valley, serene landscape stretching behind her. Adventure lifestyle photography.',
      negative_prompt: 'urban, indoor, dark, crowded, text',
      model: 'gemini-3-pro-image-preview',
      style: { aspect_ratio: '9:16' },
      ref_dependencies: ['ref_aud01_landscape'],
      output_path: 'Female 18-24/scene_02/lifestyle_shot.png',
      priority: 1,
      audience_id: 'aud_01',
      audience_name: 'Female 18-24',
    },
  ],
  text_items: [],
};

// Mock run history
export const MOCK_RUNS = [
  {
    id: 'run_9a2b3c4d',
    type: 'adapt',
    label: 'Korea Summer 2026 · 15 Jun',
    pipeline_run_id: 'run_9a2b3c4d',
    market: 'Korea',
    created_at: '2026-06-30T09:00:00Z',
    status: 'active',
  },
  {
    id: 'run_5e6f7a8b',
    type: 'adapt',
    label: '4-audience adapt · 1 Apr',
    pipeline_run_id: 'run_5e6f7a8b',
    market: 'Korea',
    created_at: '2026-04-01T10:00:00Z',
    status: 'completed',
  },
];

// Initial ref/job status (all pending)
export function buildInitialStatuses(manifest) {
  const refStatus = {};
  for (const ref of manifest.reference_images) {
    refStatus[ref.ref_id] = { status: 'pending', gcs_uri: null };
  }
  const jobStatus = {};
  for (const job of manifest.jobs) {
    jobStatus[job.job_id] = { status: 'pending', gcs_uri: null };
  }
  return { refStatus, jobStatus };
}
