/**
 * Generative AI Client for V3 Creative Engine
 * Phase 2: Real AI Generation with Imagen 3 (Vertex AI) and Veo 3.1 (Gemini API)
 * Generated by Marco (Backend Specialist)
 *
 * Image Generation: Uses Vertex AI Imagen 3 with OAuth
 * Video Generation: Uses Gemini API Veo 3.1 Fast with API Key
 */

const { VertexAI } = require('@google-cloud/vertexai');
const { GoogleAuth } = require('google-auth-library');

class GeminiClient {
  constructor(apiKey, projectId, location = 'us-central1') {
    this.apiKey = apiKey; // Gemini API key for video generation
    this.projectId = projectId;
    this.location = location;

    // Initialize Vertex AI client for image generation
    // Will use Application Default Credentials or GOOGLE_APPLICATION_CREDENTIALS
    this.vertexAI = new VertexAI({
      project: projectId,
      location: location
    });

    console.log(`[GeminiClient] Initialized with project: ${projectId}, location: ${location}`);
    console.log(`[GeminiClient] Image: Vertex AI Imagen 3 | Video: Gemini API Veo 3.1 Fast`);
  }

  /**
   * Generate image using Vertex AI Imagen 3
   * @param {string} prompt - Text prompt for image generation
   * @param {string} format - Aspect ratio: '1:1', '16:9', '9:16', '4:3'
   * @returns {Object} { data: base64String, metadata: {...} }
   */
  async generateImage(prompt, format = '1:1') {
    console.log(`[VertexAI] Generating image with Imagen 3: "${prompt}"`);

    try {
      const aspectRatio = this._formatToAspectRatio(format);

      console.log(`[VertexAI] Calling Imagen 3 API directly with aspectRatio: ${aspectRatio}`);

      // Use the direct REST API call for Imagen
      const imageResponse = await this._generateImageDirect(prompt, aspectRatio);

      return {
        data: imageResponse.bytesBase64Encoded,
        metadata: {
          prompt,
          format,
          aspectRatio,
          width: this._getWidth(format),
          height: this._getHeight(format),
          mimeType: 'image/png',
          model: 'imagen-3.0-generate-001',
          note: 'Generated by Vertex AI Imagen 3'
        }
      };

    } catch (error) {
      console.error('[VertexAI] Imagen 3 generation failed:', error);
      console.error('[VertexAI] Error details:', error.message);

      // Fallback to placeholder on error
      return this._generatePlaceholderImage(prompt, format);
    }
  }

  /**
   * Direct Imagen API call using REST API
   * Uses Google Auth to get access token and make authenticated request
   */
  async _generateImageDirect(prompt, aspectRatio) {
    const auth = new GoogleAuth({
      scopes: ['https://www.googleapis.com/auth/cloud-platform']
    });

    const client = await auth.getClient();
    const accessToken = await client.getAccessToken();

    const endpoint = `https://${this.location}-aiplatform.googleapis.com/v1/projects/${this.projectId}/locations/${this.location}/publishers/google/models/imagen-3.0-generate-001:predict`;

    const requestBody = {
      instances: [{
        prompt: prompt,
      }],
      parameters: {
        sampleCount: 1,
        aspectRatio: aspectRatio,
        safetyFilterLevel: 'block_some',
        personGeneration: 'allow_adult',
      }
    };

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const errorData = await response.text();
      throw new Error(`Imagen API error: ${response.status} - ${errorData}`);
    }

    const result = await response.json();

    // Extract base64 encoded image from response
    // Response format: { predictions: [{ bytesBase64Encoded: "..." }] }
    if (!result.predictions || !result.predictions[0]) {
      throw new Error('No image data in Imagen response');
    }

    return {
      bytesBase64Encoded: result.predictions[0].bytesBase64Encoded
    };
  }

  /**
   * Start video generation using Gemini API Veo 3.1 Fast (image-to-video)
   * @param {string} prompt - Text prompt for video generation
   * @param {string} format - Aspect ratio: '16:9', '9:16', '1:1', '4:3'
   * @param {string} imageUrl - URL of source image to animate
   * @returns {Object} { operationId: string, metadata: {...} }
   */
  async generateVideo(prompt, format = '16:9', imageUrl = null) {
    console.log(`[GeminiAPI] Starting video generation with Veo 3.1 Fast: "${prompt}"`);

    try {
      const aspectRatio = this._formatToAspectRatio(format);

      console.log(`[GeminiAPI] Video request - Format: ${format}, Aspect: ${aspectRatio}`);

      // Download image and convert to base64
      let imageBase64 = null;
      let imageMimeType = 'image/png';

      if (imageUrl) {
        console.log(`[GeminiAPI] Downloading source image: ${imageUrl}`);
        const imageResponse = await fetch(imageUrl);
        if (!imageResponse.ok) {
          throw new Error(`Failed to download image: ${imageResponse.status}`);
        }

        const imageBuffer = await imageResponse.arrayBuffer();
        imageBase64 = Buffer.from(imageBuffer).toString('base64');

        // Detect MIME type from URL or content-type
        const contentType = imageResponse.headers.get('content-type');
        if (contentType) {
          imageMimeType = contentType;
        } else if (imageUrl.endsWith('.jpg') || imageUrl.endsWith('.jpeg')) {
          imageMimeType = 'image/jpeg';
        } else if (imageUrl.endsWith('.png')) {
          imageMimeType = 'image/png';
        }

        console.log(`[GeminiAPI] Image downloaded: ${imageBase64.length} bytes, MIME: ${imageMimeType}`);
      } else {
        console.log(`[GeminiAPI] No image provided - will generate text-to-video`);
      }

      // Call Gemini API Veo 3.1 Fast with image
      const result = await this._generateVideoGeminiAPI(prompt, aspectRatio, imageBase64, imageMimeType);

      const metadata = {
        prompt,
        format,
        aspectRatio,
        duration: '5s',
        width: this._getWidth(format),
        height: this._getHeight(format),
        mimeType: 'video/mp4',
        model: 'veo-3.1-fast-generate-preview'
      };

      // Add source image reference only for image-to-video
      if (imageUrl) {
        metadata.sourceImage = imageUrl;
        metadata.mode = 'image-to-video';
      } else {
        metadata.mode = 'text-to-video';
      }

      // Veo 3.1 Fast is always async
      console.log(`[GeminiAPI] Video generation is async`);
      return {
        operationId: result.operationName,
        metadata: {
          ...metadata,
          note: 'Video generation in progress (async operation)',
          estimatedCompletionMinutes: '1-2'
        }
      };

    } catch (error) {
      console.error('[GeminiAPI] Veo generation failed:', error);
      console.error('[GeminiAPI] Error details:', error.message);

      // Re-throw error so jobProcessor can handle it
      throw error;
    }
  }

  /**
   * Gemini API Veo 3.1 Fast video generation
   * Uses simpler API key authentication instead of OAuth
   * @returns {Object} { operationName: string }
   */
  async _generateVideoGeminiAPI(prompt, aspectRatio, imageBase64 = null, imageMimeType = 'image/png') {
    // Gemini API base URL
    const baseUrl = 'https://generativelanguage.googleapis.com/v1beta';
    const model = 'veo-3.1-fast-generate-preview';
    const endpoint = `${baseUrl}/models/${model}:predictLongRunning`;

    console.log(`[GeminiAPI] Calling ${model} endpoint`);

    // Build instance object
    const instance = {
      prompt: prompt
    };

    // Add reference image if provided (image-to-video)
    if (imageBase64) {
      instance.image = {
        bytesBase64Encoded: imageBase64,
        mimeType: imageMimeType
      };
      console.log(`[GeminiAPI] IMAGE-TO-VIDEO mode - Image size: ${imageBase64.length} bytes`);
    } else {
      console.log(`[GeminiAPI] TEXT-TO-VIDEO mode`);
    }

    // Build request body with instances and parameters
    const requestBody = {
      instances: [instance],
      parameters: {
        aspectRatio: aspectRatio
      }
    };

    console.log(`[GeminiAPI] Aspect ratio: ${aspectRatio}`);

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'x-goog-api-key': this.apiKey,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const errorData = await response.text();
      throw new Error(`Gemini API error: ${response.status} - ${errorData}`);
    }

    const result = await response.json();

    console.log(`[GeminiAPI] Response received:`, JSON.stringify(result, null, 2));

    // Gemini API returns operation name
    if (result.name) {
      console.log(`[GeminiAPI] Async operation started: ${result.name}`);
      return {
        operationName: result.name
      };
    } else {
      throw new Error('Unexpected Gemini API response format - no operation name returned');
    }
  }

  /**
   * Direct Veo 3 Fast API call (DEPRECATED - using Gemini API instead)
   * Supports both text-to-video and image-to-video
   * Uses predictLongRunning
   */
  async _generateVideoDirect(prompt, aspectRatio, imageBase64 = null, imageMimeType = 'image/png') {
    const auth = new GoogleAuth({
      scopes: ['https://www.googleapis.com/auth/cloud-platform']
    });

    const client = await auth.getClient();
    const accessToken = await client.getAccessToken();

    // Veo 3 Fast endpoint
    const endpoint = `https://${this.location}-aiplatform.googleapis.com/v1/projects/${this.projectId}/locations/${this.location}/publishers/google/models/veo-3.0-fast-generate-001:predictLongRunning`;

    const veoAspectRatio = aspectRatio === '9:16' ? '16:9' : aspectRatio;

    // Build instance based on whether we have an image or not
    const instance = {
      prompt: prompt
    };

    // Add image if provided (image-to-video)
    if (imageBase64) {
      instance.image = {
        bytesBase64Encoded: imageBase64,
        mimeType: imageMimeType
      };
    }

    const requestBody = {
      instances: [instance],
      parameters: {
        sampleCount: 1,
        aspectRatio: veoAspectRatio,
        videoDuration: '5s',
      }
    };

    if (imageBase64) {
      console.log(`[VertexAI] Calling Veo 3 Fast IMAGE-TO-VIDEO endpoint`);
      console.log(`[VertexAI] Image MIME type: ${imageMimeType}`);
    } else {
      console.log(`[VertexAI] Calling Veo 3 Fast TEXT-TO-VIDEO endpoint`);
    }
    console.log(`[VertexAI] Aspect ratio: ${veoAspectRatio}`);

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const errorData = await response.text();
      throw new Error(`Veo API error: ${response.status} - ${errorData}`);
    }

    const result = await response.json();

    console.log(`[VertexAI] Veo response received`);
    console.log(`[VertexAI] Response keys: ${Object.keys(result).join(', ')}`);

    // Veo 3 Fast returns operation for long-running generation
    if (result.name) {
      console.log(`[VertexAI] Async operation started: ${result.name}`);
      return {
        operationId: result.name,
        operationMetadata: result.metadata,
        isSynchronous: false
      };
    } else {
      throw new Error('Unexpected Veo API response format - no operation ID returned');
    }
  }

  /**
   * Check status of long-running Veo operation using Gemini API
   * @param {string} operationName - The operation name from Gemini API
   * @returns {Object} { done: boolean, videoUri: string|null, error: string|null }
   */
  async checkVideoOperationStatus(operationName) {
    console.log(`[GeminiAPI] Checking operation status: ${operationName}`);

    // Gemini API operation polling endpoint
    // Format: https://generativelanguage.googleapis.com/v1beta/{OPERATION_NAME}
    const baseUrl = 'https://generativelanguage.googleapis.com/v1beta';
    const endpoint = `${baseUrl}/${operationName}`;

    console.log(`[GeminiAPI] Polling endpoint: ${endpoint}`);

    try {
      const response = await fetch(endpoint, {
        method: 'GET',
        headers: {
          'x-goog-api-key': this.apiKey,
          'Content-Type': 'application/json',
        }
      });

      if (!response.ok) {
        const errorData = await response.text();
        throw new Error(`Operation status check failed: ${response.status} - ${errorData}`);
      }

      const result = await response.json();

      console.log(`[GeminiAPI] Operation status response:`, JSON.stringify(result, null, 2));

      // Check if operation is done
      if (result.done) {
        console.log(`[GeminiAPI] Operation completed`);

        // Check for errors
        if (result.error) {
          console.error(`[GeminiAPI] Operation failed:`, result.error);
          return {
            done: true,
            videoUri: null,
            error: result.error.message || 'Video generation failed'
          };
        }

        // Extract video URI from response
        // Gemini API returns a download URI in a nested structure
        // Response format: { done: true, response: { generateVideoResponse: { generatedSamples: [{ video: { uri: "..." } }] } } }
        if (result.response &&
            result.response.generateVideoResponse &&
            result.response.generateVideoResponse.generatedSamples &&
            result.response.generateVideoResponse.generatedSamples[0] &&
            result.response.generateVideoResponse.generatedSamples[0].video &&
            result.response.generateVideoResponse.generatedSamples[0].video.uri) {

          const videoUri = result.response.generateVideoResponse.generatedSamples[0].video.uri;
          console.log(`[GeminiAPI] Video ready! URI: ${videoUri}`);
          return {
            done: true,
            videoUri: videoUri,
            error: null
          };
        } else {
          console.error(`[GeminiAPI] Operation done but no video URI in response`);
          console.error(`[GeminiAPI] Response structure:`, JSON.stringify(result.response, null, 2));
          return {
            done: true,
            videoUri: null,
            error: 'Operation completed but no video URI found in response'
          };
        }
      } else {
        // Still processing
        console.log(`[GeminiAPI] Operation still in progress`);
        return {
          done: false,
          videoUri: null,
          error: null
        };
      }

    } catch (error) {
      console.error(`[GeminiAPI] Failed to check operation status:`, error);
      throw error;
    }
  }

  /**
   * Convert format string to Vertex AI aspect ratio
   */
  _formatToAspectRatio(format) {
    const ratios = {
      '16:9': '16:9',
      '9:16': '9:16',
      '1:1': '1:1',
      '4:3': '4:3',
      '3:4': '3:4'
    };
    return ratios[format] || '1:1';
  }

  /**
   * Fallback placeholder image generator
   */
  _generatePlaceholderImage(prompt, format) {
    console.log('[VertexAI] Using placeholder fallback for image');

    const width = this._getWidth(format);
    const height = this._getHeight(format);

    const placeholderUrl = `https://placehold.co/${width}x${height}/1a73e8/white?text=${encodeURIComponent(prompt.substring(0, 50))}`;

    const mockDescription = `Generated image: ${prompt}. A stunning visual composition featuring vibrant colors and dynamic composition. Format: ${format}. This is a placeholder - Vertex AI generation is not yet fully configured.`;

    return {
      url: placeholderUrl,
      metadata: {
        prompt,
        format,
        description: mockDescription,
        width,
        height,
        mimeType: 'image/png',
        note: 'Placeholder fallback - Vertex AI not configured'
      }
    };
  }

  /**
   * Fallback placeholder video generator
   */
  _generatePlaceholderVideo(prompt, format) {
    console.log('[VertexAI] Using placeholder fallback for video');

    const width = this._getWidth(format);
    const height = this._getHeight(format);

    const placeholderUrl = `https://placehold.co/${width}x${height}/e8710a/white?text=${encodeURIComponent('▶ ' + prompt.substring(0, 50))}`;

    const mockStoryboard = `Generated video: ${prompt}. A cinematic sequence with smooth transitions and engaging visual storytelling. Format: ${format}. This is a placeholder - Vertex AI generation is not yet fully configured.`;

    return {
      url: placeholderUrl,
      metadata: {
        prompt,
        format,
        storyboard: mockStoryboard,
        width,
        height,
        mimeType: 'video/mp4',
        note: 'Placeholder fallback - Vertex AI not configured'
      }
    };
  }

  _getWidth(format) {
    const formats = {
      '16:9': 1920,
      '9:16': 1080,
      '1:1': 1024,
      '4:3': 1024,
      '3:4': 768
    };
    return formats[format] || 1024;
  }

  _getHeight(format) {
    const formats = {
      '16:9': 1080,
      '9:16': 1920,
      '1:1': 1024,
      '4:3': 768,
      '3:4': 1024
    };
    return formats[format] || 1024;
  }
}

module.exports = GeminiClient;
