/**
 * Vertex AI Client for V3 Creative Engine
 * Phase 2: Real AI Generation with Imagen 3 and Veo
 * Generated by Marco (Backend Specialist)
 */

const { VertexAI } = require('@google-cloud/vertexai');
const { GoogleAuth } = require('google-auth-library');

class GeminiClient {
  constructor(apiKey, projectId, location = 'us-central1') {
    this.projectId = projectId;
    this.location = location;

    // Initialize Vertex AI client
    // Will use Application Default Credentials or GOOGLE_APPLICATION_CREDENTIALS
    this.vertexAI = new VertexAI({
      project: projectId,
      location: location
    });

    console.log(`[VertexAI] Initialized with project: ${projectId}, location: ${location}`);
  }

  /**
   * Generate image using Vertex AI Imagen 3
   * @param {string} prompt - Text prompt for image generation
   * @param {string} format - Aspect ratio: '1:1', '16:9', '9:16', '4:3'
   * @returns {Object} { data: base64String, metadata: {...} }
   */
  async generateImage(prompt, format = '1:1') {
    console.log(`[VertexAI] Generating image with Imagen 3: "${prompt}"`);

    try {
      const aspectRatio = this._formatToAspectRatio(format);

      console.log(`[VertexAI] Calling Imagen 3 API directly with aspectRatio: ${aspectRatio}`);

      // Use the direct REST API call for Imagen
      const imageResponse = await this._generateImageDirect(prompt, aspectRatio);

      return {
        data: imageResponse.bytesBase64Encoded,
        metadata: {
          prompt,
          format,
          aspectRatio,
          width: this._getWidth(format),
          height: this._getHeight(format),
          mimeType: 'image/png',
          model: 'imagen-3.0-generate-001',
          note: 'Generated by Vertex AI Imagen 3'
        }
      };

    } catch (error) {
      console.error('[VertexAI] Imagen 3 generation failed:', error);
      console.error('[VertexAI] Error details:', error.message);

      // Fallback to placeholder on error
      return this._generatePlaceholderImage(prompt, format);
    }
  }

  /**
   * Direct Imagen API call using REST API
   * Uses Google Auth to get access token and make authenticated request
   */
  async _generateImageDirect(prompt, aspectRatio) {
    const auth = new GoogleAuth({
      scopes: ['https://www.googleapis.com/auth/cloud-platform']
    });

    const client = await auth.getClient();
    const accessToken = await client.getAccessToken();

    const endpoint = `https://${this.location}-aiplatform.googleapis.com/v1/projects/${this.projectId}/locations/${this.location}/publishers/google/models/imagen-3.0-generate-001:predict`;

    const requestBody = {
      instances: [{
        prompt: prompt,
      }],
      parameters: {
        sampleCount: 1,
        aspectRatio: aspectRatio,
        safetyFilterLevel: 'block_some',
        personGeneration: 'allow_adult',
      }
    };

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const errorData = await response.text();
      throw new Error(`Imagen API error: ${response.status} - ${errorData}`);
    }

    const result = await response.json();

    // Extract base64 encoded image from response
    // Response format: { predictions: [{ bytesBase64Encoded: "..." }] }
    if (!result.predictions || !result.predictions[0]) {
      throw new Error('No image data in Imagen response');
    }

    return {
      bytesBase64Encoded: result.predictions[0].bytesBase64Encoded
    };
  }

  /**
   * Start video generation using Vertex AI Veo 3
   * Returns operation ID instead of actual video (async operation)
   * @param {string} prompt - Text prompt for video generation
   * @param {string} format - Aspect ratio: '16:9', '9:16', '1:1', '4:3'
   * @returns {Object} { operationId: string, metadata: {...} }
   */
  async generateVideo(prompt, format = '16:9') {
    console.log(`[VertexAI] Starting video generation with Veo 3: "${prompt}"`);

    try {
      const aspectRatio = this._formatToAspectRatio(format);

      console.log(`[VertexAI] Video request - Format: ${format}, Aspect: ${aspectRatio}`);

      // Start long-running operation
      const operationInfo = await this._generateVideoDirect(prompt, aspectRatio);

      return {
        operationId: operationInfo.operationId,
        metadata: {
          prompt,
          format,
          aspectRatio,
          duration: '5s',
          width: this._getWidth(format),
          height: this._getHeight(format),
          mimeType: 'video/mp4',
          model: 'veo-3.0-generate-preview',
          note: 'Video generation in progress (async operation)',
          estimatedCompletionMinutes: 3-5
        }
      };

    } catch (error) {
      console.error('[VertexAI] Veo generation start failed:', error);
      console.error('[VertexAI] Error details:', error.message);

      // Re-throw error so jobProcessor can handle it
      throw error;
    }
  }

  /**
   * Direct Veo API call using REST API
   * Starts a long-running video generation operation
   * Returns operation ID that must be polled for completion
   */
  async _generateVideoDirect(prompt, aspectRatio) {
    const auth = new GoogleAuth({
      scopes: ['https://www.googleapis.com/auth/cloud-platform']
    });

    const client = await auth.getClient();
    const accessToken = await client.getAccessToken();

    // Veo 3 endpoint - uses predictLongRunning for async video generation
    const endpoint = `https://${this.location}-aiplatform.googleapis.com/v1/projects/${this.projectId}/locations/${this.location}/publishers/google/models/veo-3.0-generate-preview:predictLongRunning`;

    // Note: Veo 3 doesn't support 9:16 aspect ratio, fallback to 16:9
    const veoAspectRatio = aspectRatio === '9:16' ? '16:9' : aspectRatio;

    const requestBody = {
      instances: [{
        prompt: prompt,
      }],
      parameters: {
        sampleCount: 1,
        aspectRatio: veoAspectRatio,
        videoDuration: '5s',
      }
    };

    console.log(`[VertexAI] Starting Veo 3 long-running operation`);
    console.log(`[VertexAI] Aspect ratio: ${veoAspectRatio}`);

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const errorData = await response.text();
      throw new Error(`Veo API error: ${response.status} - ${errorData}`);
    }

    const result = await response.json();

    // Extract operation ID
    if (!result.name) {
      throw new Error('No operation ID returned from Veo API');
    }

    console.log(`[VertexAI] Veo operation started: ${result.name}`);

    // Return operation info for polling
    return {
      operationId: result.name,
      operationMetadata: result.metadata
    };
  }

  /**
   * Check status of long-running Veo operation
   * @param {string} operationId - The operation ID from _generateVideoDirect
   * @returns {Object} { done: boolean, video: base64String|null, error: string|null }
   */
  async checkVideoOperationStatus(operationId) {
    const auth = new GoogleAuth({
      scopes: ['https://www.googleapis.com/auth/cloud-platform']
    });

    const client = await auth.getClient();
    const accessToken = await client.getAccessToken();

    // Get operation status
    const endpoint = `https://${this.location}-aiplatform.googleapis.com/v1/${operationId}`;

    console.log(`[VertexAI] Checking operation status: ${operationId}`);

    const response = await fetch(endpoint, {
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${accessToken.token}`,
      }
    });

    if (!response.ok) {
      const errorData = await response.text();
      throw new Error(`Operation status check failed: ${response.status} - ${errorData}`);
    }

    const result = await response.json();

    // Check if operation is complete
    if (result.done) {
      console.log(`[VertexAI] Operation complete!`);

      // Check for errors
      if (result.error) {
        return {
          done: true,
          video: null,
          error: result.error.message || 'Video generation failed'
        };
      }

      // Extract video data
      if (result.response && result.response.predictions && result.response.predictions[0]) {
        const videoData = result.response.predictions[0].bytesBase64Encoded;
        return {
          done: true,
          video: videoData,
          error: null
        };
      }

      return {
        done: true,
        video: null,
        error: 'No video data in response'
      };
    }

    // Still processing
    console.log(`[VertexAI] Operation still processing...`);
    return {
      done: false,
      video: null,
      error: null
    };
  }

  /**
   * Convert format string to Vertex AI aspect ratio
   */
  _formatToAspectRatio(format) {
    const ratios = {
      '16:9': '16:9',
      '9:16': '9:16',
      '1:1': '1:1',
      '4:3': '4:3',
      '3:4': '3:4'
    };
    return ratios[format] || '1:1';
  }

  /**
   * Fallback placeholder image generator
   */
  _generatePlaceholderImage(prompt, format) {
    console.log('[VertexAI] Using placeholder fallback for image');

    const width = this._getWidth(format);
    const height = this._getHeight(format);

    const placeholderUrl = `https://placehold.co/${width}x${height}/1a73e8/white?text=${encodeURIComponent(prompt.substring(0, 50))}`;

    const mockDescription = `Generated image: ${prompt}. A stunning visual composition featuring vibrant colors and dynamic composition. Format: ${format}. This is a placeholder - Vertex AI generation is not yet fully configured.`;

    return {
      url: placeholderUrl,
      metadata: {
        prompt,
        format,
        description: mockDescription,
        width,
        height,
        mimeType: 'image/png',
        note: 'Placeholder fallback - Vertex AI not configured'
      }
    };
  }

  /**
   * Fallback placeholder video generator
   */
  _generatePlaceholderVideo(prompt, format) {
    console.log('[VertexAI] Using placeholder fallback for video');

    const width = this._getWidth(format);
    const height = this._getHeight(format);

    const placeholderUrl = `https://placehold.co/${width}x${height}/e8710a/white?text=${encodeURIComponent('▶ ' + prompt.substring(0, 50))}`;

    const mockStoryboard = `Generated video: ${prompt}. A cinematic sequence with smooth transitions and engaging visual storytelling. Format: ${format}. This is a placeholder - Vertex AI generation is not yet fully configured.`;

    return {
      url: placeholderUrl,
      metadata: {
        prompt,
        format,
        storyboard: mockStoryboard,
        width,
        height,
        mimeType: 'video/mp4',
        note: 'Placeholder fallback - Vertex AI not configured'
      }
    };
  }

  _getWidth(format) {
    const formats = {
      '16:9': 1920,
      '9:16': 1080,
      '1:1': 1024,
      '4:3': 1024,
      '3:4': 768
    };
    return formats[format] || 1024;
  }

  _getHeight(format) {
    const formats = {
      '16:9': 1080,
      '9:16': 1920,
      '1:1': 1024,
      '4:3': 768,
      '3:4': 1024
    };
    return formats[format] || 1024;
  }
}

module.exports = GeminiClient;
