/**
 * Cloud Functions Index for V3 Creative Engine
 * Generated by Marco (Backend Specialist)
 */

// Load environment variables from .env file
require('dotenv').config();

const admin = require('firebase-admin');
const functions = require('firebase-functions');

// Initialize Firebase Admin
admin.initializeApp();

// Import handlers
const { processJob } = require('./jobProcessor');
const { createTestJob } = require('./testJob');
const { regenerateJob } = require('./regenerateJob');
const { upscaleJob } = require('./upscaleJob');
const { imageToVideoJob } = require('./imageToVideoJob');
const { expandImageJob } = require('./expandImageJob');
const { iterateJob } = require('./iterateJob');
const { importPrompt } = require('./importPrompt');
const { callGeminiAgent } = require('./callGeminiAgent');
const { pollVideoOperations } = require('./videoPoller');
const { downloadAsset } = require('./downloadAsset');

// Job processor (Firestore trigger)
exports.processJob = functions.firestore
  .document('jobs/{jobId}')
  .onCreate(processJob);

// Test job creation endpoint (Callable)
exports.createTestJob = functions.https.onCall(createTestJob);

// Regenerate job endpoint (HTTP)
exports.regenerateJob = functions.https.onCall(regenerateJob);

// Upscale job endpoint (HTTP)
exports.upscaleJob = functions.https.onCall(upscaleJob);

// Image to video endpoint (HTTP)
exports.imageToVideoJob = functions.https.onCall(imageToVideoJob);

// Expand image endpoint (HTTP)
exports.expandImageJob = functions.https.onCall(expandImageJob);

// Iterate job endpoint (HTTP) - Create variations
exports.iterateJob = functions.https.onCall(iterateJob);

// MCP Bridge - Import prompt from external sources (HTTP endpoint)
exports.importPrompt = functions.https.onRequest(importPrompt);

// Gemini Agent - Secure server-side API calls (Callable)
exports.callGeminiAgent = functions.https.onCall(callGeminiAgent);

// Video Operation Poller - Checks status of long-running video operations (PubSub, scheduled every minute)
exports.pollVideoOperations = functions.pubsub
  .topic('video-operations-poll')
  .onPublish(pollVideoOperations);

// Download Asset - Proxy for downloading files with proper CORS headers (HTTP endpoint)
exports.downloadAsset = functions.https.onRequest(downloadAsset);

// Shorts Intel Hub functions (ES Modules)
// Note: These are exported directly from shorts-intel-hub/index.js using ES module syntax
// To deploy: Use codebase configuration in firebase.json
exports.shortsIntelApi = require('./shorts-intel-hub-wrapper').shortsIntelApi;
exports.shortsIntelWeeklyRefresh = require('./shorts-intel-hub-wrapper').shortsIntelWeeklyRefresh;

console.log('[V3 Functions] Cloud Functions initialized');
