/**
 * Job Processor for V3 Creative Engine
 * Generated by Marco (Backend Specialist)
 */

const admin = require('firebase-admin');
const GeminiClient = require('./gemini');

async function processJob(snap, context) {
  const jobId = context.params.jobId;
  const job = snap.data();

  console.log(`[JobProcessor] Processing job ${jobId}`);

  const db = admin.firestore();
  const jobRef = db.collection('jobs').doc(jobId);

  try {
    await jobRef.update({
      status: 'processing',
      updatedAt: admin.firestore.FieldValue.serverTimestamp()
    });

    // Get configuration from environment
    const apiKey = process.env.GEMINI_API_KEY;
    const projectId = process.env.GCP_PROJECT_ID || 'v3-creative-engine';
    const location = process.env.VERTEX_AI_LOCATION || 'us-central1';

    const gemini = new GeminiClient(apiKey, projectId, location);

    const startTime = Date.now();
    let result;

    if (job.type === 'image') {
      result = await gemini.generateImage(job.prompt, job.format || '1:1');

      // Upload actual image data to Cloud Storage if available
      if (result.data) {
        console.log(`[JobProcessor] Uploading image to Cloud Storage for job ${jobId}`);
        const storageUrl = await uploadImageToStorage(jobId, result.data);
        result.url = storageUrl;
        delete result.data; // Remove base64 data from result
      }

      const processingTimeMs = Date.now() - startTime;

      await jobRef.update({
        status: 'complete',
        result: { url: result.url, metadata: result.metadata },
        processedAt: admin.firestore.FieldValue.serverTimestamp(),
        processingTimeMs,
        updatedAt: admin.firestore.FieldValue.serverTimestamp()
      });

      console.log(`[JobProcessor] Job ${jobId} completed in ${processingTimeMs}ms`);

    } else {
      // VIDEO: Start long-running operation
      result = await gemini.generateVideo(job.prompt, job.format || '16:9');

      const processingTimeMs = Date.now() - startTime;

      // Update job with operation ID and set status to 'generating'
      await jobRef.update({
        status: 'generating',
        operationId: result.operationId,
        result: {
          metadata: result.metadata,
          estimatedMinutes: '3-5',
          message: 'Video generation in progress...'
        },
        startedAt: admin.firestore.FieldValue.serverTimestamp(),
        processingTimeMs,
        updatedAt: admin.firestore.FieldValue.serverTimestamp()
      });

      console.log(`[JobProcessor] Video operation started: ${result.operationId}`);
      console.log(`[JobProcessor] Job ${jobId} will be polled for completion`);
    }

  } catch (error) {
    console.error(`[JobProcessor] Job ${jobId} failed:`, error);
    await jobRef.update({
      status: 'error',
      error: error.message,
      updatedAt: admin.firestore.FieldValue.serverTimestamp()
    });
    throw error;
  }
}

/**
 * Upload image to Cloud Storage
 * @param {string} jobId - Job ID
 * @param {string} base64Data - Base64 encoded image data
 * @returns {string} Public URL of uploaded image
 */
async function uploadImageToStorage(jobId, base64Data) {
  const bucket = admin.storage().bucket();
  const fileName = `images/${jobId}.png`;
  const file = bucket.file(fileName);

  // Convert base64 to buffer
  const buffer = Buffer.from(base64Data, 'base64');

  console.log(`[JobProcessor] Uploading image: ${fileName} (${buffer.length} bytes)`);

  await file.save(buffer, {
    metadata: {
      contentType: 'image/png',
      metadata: {
        jobId: jobId,
        generatedAt: new Date().toISOString()
      }
    },
    public: true,
    resumable: false // Faster for small files
  });

  // Get public URL
  const publicUrl = `https://storage.googleapis.com/${bucket.name}/${fileName}`;

  console.log(`[JobProcessor] Image uploaded: ${publicUrl}`);

  return publicUrl;
}

/**
 * Upload video to Cloud Storage
 * @param {string} jobId - Job ID
 * @param {string} base64Data - Base64 encoded video data
 * @returns {string} Public URL of uploaded video
 */
async function uploadVideoToStorage(jobId, base64Data) {
  const bucket = admin.storage().bucket();
  const fileName = `videos/${jobId}.mp4`;
  const file = bucket.file(fileName);

  // Convert base64 to buffer
  const buffer = Buffer.from(base64Data, 'base64');

  console.log(`[JobProcessor] Uploading video: ${fileName} (${buffer.length} bytes)`);

  await file.save(buffer, {
    metadata: {
      contentType: 'video/mp4',
      metadata: {
        jobId: jobId,
        generatedAt: new Date().toISOString()
      }
    },
    public: true,
    resumable: false
  });

  // Get public URL
  const publicUrl = `https://storage.googleapis.com/${bucket.name}/${fileName}`;

  console.log(`[JobProcessor] Video uploaded: ${publicUrl}`);

  return publicUrl;
}

module.exports = { processJob };
