/**
 * Test Job Endpoint for V3 Creative Engine
 * Generated by Marco (Backend Specialist)
 * Updated to use onCall for Firebase callable functions
 */

const admin = require('firebase-admin');

async function createTestJob(data, context) {
  try {
    const { type = 'image', prompt, format, sceneNumber, country } = data;

    const db = admin.firestore();
    const jobRef = await db.collection('jobs').add({
      status: 'pending',
      type: type,
      prompt: prompt || `Test ${type} generation`,
      format: format || (type === 'image' ? '1:1' : '16:9'),
      sceneNumber: sceneNumber || null,
      country: country || 'korea',  // Default to korea if not specified
      context: { source: 'ytm-generator' },
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      updatedAt: admin.firestore.FieldValue.serverTimestamp()
    });

    console.log(`[TestJob] Created test job: ${jobRef.id}`);

    return {
      success: true,
      jobId: jobRef.id,
      message: `Test ${type} job created`
    };

  } catch (error) {
    console.error('[TestJob] Error:', error);
    throw new Error(error.message);
  }
}

module.exports = { createTestJob };
