/**
 * Generative AI Client for V3 Creative Engine
 * Phase 2: Real AI Generation with Imagen 3 (Vertex AI) and Veo 3.1 (Gemini API)
 * Generated by Marco (Backend Specialist)
 *
 * Image Generation: Uses Vertex AI Imagen 3 with OAuth
 * Video Generation: Uses Gemini API Veo 3.1 Fast with API Key
 */

const { VertexAI } = require('@google-cloud/vertexai');
const { GoogleAuth } = require('google-auth-library');

class GeminiClient {
  constructor(apiKey, projectId, location = 'us-central1') {
    this.apiKey = apiKey; // Gemini API key for video generation
    this.projectId = projectId;
    this.location = location;

    // Initialize Vertex AI client for image generation
    // Will use Application Default Credentials or GOOGLE_APPLICATION_CREDENTIALS
    this.vertexAI = new VertexAI({
      project: projectId,
      location: location
    });

    console.log(`[GeminiClient] Initialized with project: ${projectId}, location: ${location}`);
    console.log(`[GeminiClient] Image: Vertex AI Imagen 3 | Video: Gemini API Veo 3.1 Fast`);
  }

  /**
   * Generate image using Vertex AI Imagen 3
   * @param {string} prompt - Text prompt for image generation
   * @param {string} format - Aspect ratio: '1:1', '16:9', '9:16', '4:3'
   * @param {string} referenceImageUrl - Optional reference image URL for editing/expansion
   * @param {Object} options - Optional generation options (e.g., { expandMode: true, referenceImages: [] })
   * @returns {Object} { data: base64String, metadata: {...} }
   */
  async generateImage(prompt, format = '1:1', referenceImageUrl = null, options = {}) {
    console.log(`[VertexAI] Generating image with Imagen 3: "${prompt}"`);

    // Enhanced prompt for expand mode
    let enhancedPrompt = prompt;
    if (referenceImageUrl && options.expandMode) {
      console.log(`[VertexAI] EXPAND MODE - using enhanced prompt for zoomed-out perspective`);
      // Create a detailed prompt that asks for a zoomed-out version
      enhancedPrompt = `Wide-angle, zoomed-out view of: ${prompt}. Camera pulled back significantly to show much more of the surrounding environment and context. Same subject, same scene, same lighting and atmosphere, but from a wider perspective that reveals the broader setting. Maintain the core composition but expand the field of view to show what's around and beyond the original frame.`;
      console.log(`[VertexAI] Enhanced prompt for expansion`);
    }

    try {
      const aspectRatio = this._formatToAspectRatio(format);

      console.log(`[VertexAI] Calling Imagen 3 API directly with aspectRatio: ${aspectRatio}`);

      // Check if reference images are provided (Nano Banana Pro mode)
      if (options.referenceImages && options.referenceImages.length > 0) {
        console.log(`[VertexAI] NANO BANANA PRO MODE - Using ${options.referenceImages.length} reference image(s)`);
        const imageResponse = await this._generateImageWithReferences(enhancedPrompt, aspectRatio, options.referenceImages);
        return {
          data: imageResponse.bytesBase64Encoded,
          metadata: {
            prompt: enhancedPrompt,
            originalPrompt: prompt,
            format,
            aspectRatio,
            width: this._getWidth(format),
            height: this._getHeight(format),
            mimeType: 'image/png',
            model: 'imagen-3.0-generate-001',
            note: 'Generated by Vertex AI Imagen 3 with reference images (Nano Banana Pro)',
            referenceImagesCount: options.referenceImages.length
          }
        };
      }

      // Use standard generation with enhanced prompt
      const imageResponse = await this._generateImageDirect(enhancedPrompt, aspectRatio);

      return {
        data: imageResponse.bytesBase64Encoded,
        metadata: {
          prompt: enhancedPrompt,
          originalPrompt: prompt,
          format,
          aspectRatio,
          width: this._getWidth(format),
          height: this._getHeight(format),
          mimeType: 'image/png',
          model: 'imagen-3.0-generate-001',
          note: options.expandMode ? 'Generated by Vertex AI Imagen 3 (expanded view)' : 'Generated by Vertex AI Imagen 3',
          ...(options.expandMode && { mode: 'expand' }),
          ...(referenceImageUrl && { referenceImage: referenceImageUrl })
        }
      };

    } catch (error) {
      console.error('[VertexAI] Imagen 3 generation failed:', error);
      console.error('[VertexAI] Error details:', error.message);

      // Fallback to placeholder on error
      return this._generatePlaceholderImage(prompt, format);
    }
  }

  /**
   * Direct Imagen API call using REST API
   * Uses Google Auth to get access token and make authenticated request
   * Standard text-to-image generation only
   */
  async _generateImageDirect(prompt, aspectRatio) {
    const auth = new GoogleAuth({
      scopes: ['https://www.googleapis.com/auth/cloud-platform']
    });

    const client = await auth.getClient();
    const accessToken = await client.getAccessToken();

    // Use Imagen 3 endpoint - this was working on Feb 20, 2026
    const endpoint = `https://${this.location}-aiplatform.googleapis.com/v1/projects/${this.projectId}/locations/${this.location}/publishers/google/models/imagen-3.0-generate-001:predict`;

    const requestBody = {
      instances: [{
        prompt: prompt
      }],
      parameters: {
        sampleCount: 1,
        aspectRatio: aspectRatio,
        safetyFilterLevel: 'block_some',
        personGeneration: 'allow_adult',
      }
    };

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const errorData = await response.text();
      console.error(`[VertexAI] Imagen API error: ${response.status}`);
      throw new Error(`Imagen API error: ${response.status} - ${errorData}`);
    }

    const result = await response.json();

    // Extract base64 encoded image from response
    // Response format: { predictions: [{ bytesBase64Encoded: "..." }] }
    if (!result.predictions || !result.predictions[0]) {
      console.error(`[VertexAI] ERROR: Missing predictions in response`);
      throw new Error('No image data in Imagen response');
    }

    if (!result.predictions[0].bytesBase64Encoded) {
      console.error(`[VertexAI] ERROR: Missing bytesBase64Encoded in prediction`);
      throw new Error('No bytesBase64Encoded in prediction');
    }

    return {
      bytesBase64Encoded: result.predictions[0].bytesBase64Encoded
    };
  }

  /**
   * Imagen 3 image editing with outpainting support
   * Uses imagen-3.0-capability-001 model for image expansion
   */
  async _generateImageWithEditing(prompt, aspectRatio, imageBase64, imageMimeType) {
    const auth = new GoogleAuth({
      scopes: ['https://www.googleapis.com/auth/cloud-platform']
    });

    const client = await auth.getClient();
    const accessToken = await client.getAccessToken();

    const endpoint = `https://${this.location}-aiplatform.googleapis.com/v1/projects/${this.projectId}/locations/${this.location}/publishers/google/models/imagen-3.0-capability-001:predict`;

    console.log(`[VertexAI] Using imagen-3.0-capability-001 for outpainting`);

    // Build request for outpainting
    // The editing model expects context_image for mask-free editing
    const requestBody = {
      instances: [{
        prompt: `${prompt}. Expand the frame outward, zoomed-out perspective showing more of the surrounding environment while maintaining the original subject in the center.`,
        referenceImages: [{
          referenceType: 1,  // REFERENCE_TYPE_STYLE
          referenceImage: {
            bytesBase64Encoded: imageBase64
          }
        }]
      }],
      parameters: {
        sampleCount: 1,
        aspectRatio: aspectRatio,
        safetyFilterLevel: 'block_some',
        personGeneration: 'allow_adult',
      }
    };

    console.log(`[VertexAI] Outpainting request - Aspect ratio: ${aspectRatio}, Image size: ${imageBase64.length} bytes`);

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const errorData = await response.text();
      console.error(`[VertexAI] Editing model error response: ${errorData}`);
      throw new Error(`Imagen editing API error: ${response.status} - ${errorData}`);
    }

    const result = await response.json();

    console.log(`[VertexAI] Editing model response received`);

    // Extract base64 encoded image from response
    if (!result.predictions || !result.predictions[0]) {
      throw new Error('No image data in Imagen editing response');
    }

    return {
      bytesBase64Encoded: result.predictions[0].bytesBase64Encoded
    };
  }

  /**
   * Imagen 3 image generation with reference images (Nano Banana Pro capability)
   * Supports up to 14 reference images for consistent character/style/object generation
   * Uses imagen-3.0-capability-001 model for reference-based generation
   */
  async _generateImageWithReferences(prompt, aspectRatio, referenceImages) {
    const auth = new GoogleAuth({
      scopes: ['https://www.googleapis.com/auth/cloud-platform']
    });

    const client = await auth.getClient();
    const accessToken = await client.getAccessToken();

    const endpoint = `https://${this.location}-aiplatform.googleapis.com/v1/projects/${this.projectId}/locations/${this.location}/publishers/google/models/imagen-3.0-capability-001:predict`;

    console.log(`[VertexAI] Using imagen-3.0-capability-001 for reference-based generation (Nano Banana Pro)`);
    console.log(`[VertexAI] Reference images count: ${referenceImages.length}`);

    // Build reference images array
    // referenceImages is an array of { url, type } where type is 'subject' (1) or 'style' (2)
    const referenceImagesData = [];
    for (let i = 0; i < referenceImages.length; i++) {
      const ref = referenceImages[i];
      console.log(`[VertexAI] Downloading reference image ${i + 1}: ${ref.url}`);

      try {
        // Download reference image
        const imageResponse = await fetch(ref.url);
        if (!imageResponse.ok) {
          throw new Error(`Failed to download reference image: ${imageResponse.status}`);
        }

        const imageBuffer = await imageResponse.arrayBuffer();
        const imageBase64 = Buffer.from(imageBuffer).toString('base64');

        referenceImagesData.push({
          referenceType: ref.type === 'style' ? 2 : 1, // 1 = SUBJECT, 2 = STYLE
          referenceImage: {
            bytesBase64Encoded: imageBase64
          }
        });

        console.log(`[VertexAI] Reference image ${i + 1} downloaded: ${imageBase64.length} bytes, type: ${ref.type}`);
      } catch (error) {
        console.error(`[VertexAI] Failed to download reference image ${i + 1}:`, error);
        // Continue with other images
      }
    }

    if (referenceImagesData.length === 0) {
      throw new Error('No valid reference images could be downloaded');
    }

    // Build request for reference-based generation
    const requestBody = {
      instances: [{
        prompt: prompt,
        referenceImages: referenceImagesData
      }],
      parameters: {
        sampleCount: 1,
        aspectRatio: aspectRatio,
        safetyFilterLevel: 'block_some',
        personGeneration: 'allow_adult',
      }
    };

    console.log(`[VertexAI] Reference-based generation - Aspect ratio: ${aspectRatio}, References: ${referenceImagesData.length}`);

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const errorData = await response.text();
      console.error(`[VertexAI] Reference-based generation error: ${errorData}`);
      throw new Error(`Imagen reference API error: ${response.status} - ${errorData}`);
    }

    const result = await response.json();

    console.log(`[VertexAI] Reference-based generation complete`);

    // Extract base64 encoded image from response
    if (!result.predictions || !result.predictions[0]) {
      throw new Error('No image data in Imagen reference response');
    }

    return {
      bytesBase64Encoded: result.predictions[0].bytesBase64Encoded
    };
  }

  /**
   * Start video generation using Gemini API Veo 3.1 Fast (image-to-video)
   * @param {string} prompt - Text prompt for video generation
   * @param {string} format - Aspect ratio: '16:9', '9:16', '1:1', '4:3'
   * @param {string} imageUrl - URL of source image to animate
   * @returns {Object} { operationId: string, metadata: {...} }
   */
  async generateVideo(prompt, format = '16:9', imageUrl = null) {
    console.log(`[GeminiAPI] Starting video generation with Veo 3.1 Fast: "${prompt}"`);

    try {
      const aspectRatio = this._formatToAspectRatio(format);

      console.log(`[GeminiAPI] Video request - Format: ${format}, Aspect: ${aspectRatio}`);

      // Download image and convert to base64
      let imageBase64 = null;
      let imageMimeType = 'image/png';

      if (imageUrl) {
        console.log(`[GeminiAPI] Downloading source image: ${imageUrl}`);
        const imageResponse = await fetch(imageUrl);
        if (!imageResponse.ok) {
          throw new Error(`Failed to download image: ${imageResponse.status}`);
        }

        const imageBuffer = await imageResponse.arrayBuffer();
        imageBase64 = Buffer.from(imageBuffer).toString('base64');

        // Detect MIME type from URL or content-type
        const contentType = imageResponse.headers.get('content-type');
        if (contentType) {
          imageMimeType = contentType;
        } else if (imageUrl.endsWith('.jpg') || imageUrl.endsWith('.jpeg')) {
          imageMimeType = 'image/jpeg';
        } else if (imageUrl.endsWith('.png')) {
          imageMimeType = 'image/png';
        }

        console.log(`[GeminiAPI] Image downloaded: ${imageBase64.length} bytes, MIME: ${imageMimeType}`);
      } else {
        console.log(`[GeminiAPI] No image provided - will generate text-to-video`);
      }

      // Call Gemini API Veo 3.1 Fast with image
      const result = await this._generateVideoGeminiAPI(prompt, aspectRatio, imageBase64, imageMimeType);

      const metadata = {
        prompt,
        format,
        aspectRatio,
        duration: '5s',
        width: this._getWidth(format),
        height: this._getHeight(format),
        mimeType: 'video/mp4',
        model: 'veo-3.1-fast-generate-001'
      };

      // Add source image reference only for image-to-video
      if (imageUrl) {
        metadata.sourceImage = imageUrl;
        metadata.mode = 'image-to-video';
      } else {
        metadata.mode = 'text-to-video';
      }

      // Veo 3.1 Fast is always async
      console.log(`[GeminiAPI] Video generation is async`);
      return {
        operationId: result.operationName,
        metadata: {
          ...metadata,
          note: 'Video generation in progress (async operation)',
          estimatedCompletionMinutes: '1-2'
        }
      };

    } catch (error) {
      console.error('[GeminiAPI] Veo generation failed:', error);
      console.error('[GeminiAPI] Error details:', error.message);

      // Re-throw error so jobProcessor can handle it
      throw error;
    }
  }

  /**
   * Gemini API Veo 3.1 Fast video generation
   * Uses OAuth authentication (service account) instead of API key
   * @returns {Object} { operationName: string }
   */
  async _generateVideoGeminiAPI(prompt, aspectRatio, imageBase64 = null, imageMimeType = 'image/png') {
    // Use OAuth authentication (same as image generation)
    const auth = new GoogleAuth({
      scopes: ['https://www.googleapis.com/auth/cloud-platform']
    });

    const client = await auth.getClient();
    const accessToken = await client.getAccessToken();

    // Vertex AI endpoint for Veo 3.1 Fast (GA)
    const endpoint = `https://${this.location}-aiplatform.googleapis.com/v1/projects/${this.projectId}/locations/${this.location}/publishers/google/models/veo-3.1-fast-generate-001:predictLongRunning`;

    console.log(`[VertexAI] Calling veo-3.1-fast-generate-001 endpoint`);

    // Build instance object
    const instance = {
      prompt: prompt
    };

    // Add reference image if provided (image-to-video)
    if (imageBase64) {
      instance.image = {
        bytesBase64Encoded: imageBase64,
        mimeType: imageMimeType
      };
      console.log(`[VertexAI] IMAGE-TO-VIDEO mode - Image size: ${imageBase64.length} bytes`);
    } else {
      console.log(`[VertexAI] TEXT-TO-VIDEO mode`);
    }

    // Build request body with instances and parameters
    const requestBody = {
      instances: [instance],
      parameters: {
        aspectRatio: aspectRatio,
        videoDuration: '5s'
      }
    };

    console.log(`[VertexAI] Aspect ratio: ${aspectRatio}`);

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const errorData = await response.text();
      console.error(`[VertexAI] Video generation error: ${response.status}`);
      throw new Error(`Vertex AI video generation error: ${response.status} - ${errorData}`);
    }

    const result = await response.json();

    // Vertex AI returns operation name
    if (result.name) {
      console.log(`[VertexAI] Video generation started successfully`);
      return {
        operationName: result.name
      };
    } else {
      throw new Error('Unexpected Vertex AI response format - no operation name returned');
    }
  }

  /**
   * Direct Veo 3 Fast API call (DEPRECATED - using Gemini API instead)
   * Supports both text-to-video and image-to-video
   * Uses predictLongRunning
   */
  async _generateVideoDirect(prompt, aspectRatio, imageBase64 = null, imageMimeType = 'image/png') {
    const auth = new GoogleAuth({
      scopes: ['https://www.googleapis.com/auth/cloud-platform']
    });

    const client = await auth.getClient();
    const accessToken = await client.getAccessToken();

    // Veo 3 Fast endpoint
    const endpoint = `https://${this.location}-aiplatform.googleapis.com/v1/projects/${this.projectId}/locations/${this.location}/publishers/google/models/veo-3.0-fast-generate-001:predictLongRunning`;

    const veoAspectRatio = aspectRatio === '9:16' ? '16:9' : aspectRatio;

    // Build instance based on whether we have an image or not
    const instance = {
      prompt: prompt
    };

    // Add image if provided (image-to-video)
    if (imageBase64) {
      instance.image = {
        bytesBase64Encoded: imageBase64,
        mimeType: imageMimeType
      };
    }

    const requestBody = {
      instances: [instance],
      parameters: {
        sampleCount: 1,
        aspectRatio: veoAspectRatio,
        videoDuration: '5s',
      }
    };

    if (imageBase64) {
      console.log(`[VertexAI] Calling Veo 3 Fast IMAGE-TO-VIDEO endpoint`);
      console.log(`[VertexAI] Image MIME type: ${imageMimeType}`);
    } else {
      console.log(`[VertexAI] Calling Veo 3 Fast TEXT-TO-VIDEO endpoint`);
    }
    console.log(`[VertexAI] Aspect ratio: ${veoAspectRatio}`);

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const errorData = await response.text();
      throw new Error(`Veo API error: ${response.status} - ${errorData}`);
    }

    const result = await response.json();

    console.log(`[VertexAI] Veo response received`);
    console.log(`[VertexAI] Response keys: ${Object.keys(result).join(', ')}`);

    // Veo 3 Fast returns operation for long-running generation
    if (result.name) {
      console.log(`[VertexAI] Async operation started: ${result.name}`);
      return {
        operationId: result.name,
        operationMetadata: result.metadata,
        isSynchronous: false
      };
    } else {
      throw new Error('Unexpected Veo API response format - no operation ID returned');
    }
  }

  /**
   * Check status of long-running Veo operation using Vertex AI
   * @param {string} operationName - The operation name from Vertex AI
   * @returns {Object} { done: boolean, videoUri: string|null, error: string|null }
   */
  async checkVideoOperationStatus(operationName) {
    console.log(`[VertexAI] Checking operation status: ${operationName}`);

    // Use OAuth authentication
    const auth = new GoogleAuth({
      scopes: ['https://www.googleapis.com/auth/cloud-platform']
    });

    const client = await auth.getClient();
    const accessToken = await client.getAccessToken();

    // Vertex AI operation polling endpoint
    // The operationName is a full path like: projects/.../locations/.../operations/...
    const endpoint = `https://${this.location}-aiplatform.googleapis.com/v1/${operationName}`;

    try {
      const response = await fetch(endpoint, {
        method: 'GET',
        headers: {
          'Authorization': `Bearer ${accessToken.token}`,
          'Content-Type': 'application/json',
        }
      });

      if (!response.ok) {
        const errorData = await response.text();
        console.error(`[VertexAI] Status check failed: ${response.status}`);
        throw new Error(`Operation status check failed: ${response.status} - ${errorData}`);
      }

      const result = await response.json();

      // Check if operation is done
      if (result.done) {
        console.log(`[VertexAI] Operation completed`);

        // Check for errors
        if (result.error) {
          console.error(`[VertexAI] Operation failed:`, result.error);
          return {
            done: true,
            videoUri: null,
            error: result.error.message || 'Video generation failed'
          };
        }

        // Vertex AI response format: { done: true, response: { predictions: [...] } }
        // The video is returned as a base64-encoded MP4 in predictions[0].bytesBase64Encoded
        if (result.response && result.response.predictions && result.response.predictions[0]) {
          const prediction = result.response.predictions[0];

          // Check for base64 video data
          if (prediction.bytesBase64Encoded) {
            console.log(`[VertexAI] Video ready! Base64 data received`);
            return {
              done: true,
              videoData: prediction.bytesBase64Encoded,
              videoUri: null, // Will be uploaded to Cloud Storage by jobProcessor
              error: null
            };
          }

          // Check for GCS URI (alternative format)
          if (prediction.gcsUri || prediction.uri) {
            const videoUri = prediction.gcsUri || prediction.uri;
            console.log(`[VertexAI] Video ready! URI: ${videoUri}`);
            return {
              done: true,
              videoUri: videoUri,
              videoData: null,
              error: null
            };
          }
        }

        console.error(`[VertexAI] Operation done but no video data in response`);
        return {
          done: true,
          videoUri: null,
          videoData: null,
          error: 'Operation completed but no video data found in response'
        };
      } else {
        // Still processing
        console.log(`[VertexAI] Operation still in progress`);
        return {
          done: false,
          videoUri: null,
          videoData: null,
          error: null
        };
      }

    } catch (error) {
      console.error(`[VertexAI] Failed to check operation status:`, error);
      throw error;
    }
  }

  /**
   * Convert format string to Vertex AI aspect ratio
   */
  _formatToAspectRatio(format) {
    const ratios = {
      '16:9': '16:9',
      '9:16': '9:16',
      '1:1': '1:1',
      '4:3': '4:3',
      '3:4': '3:4'
    };
    return ratios[format] || '1:1';
  }

  /**
   * Fallback placeholder image generator
   */
  _generatePlaceholderImage(prompt, format) {
    console.log('[VertexAI] Using placeholder fallback for image');

    const width = this._getWidth(format);
    const height = this._getHeight(format);

    const placeholderUrl = `https://placehold.co/${width}x${height}/1a73e8/white?text=${encodeURIComponent(prompt.substring(0, 50))}`;

    const mockDescription = `Generated image: ${prompt}. A stunning visual composition featuring vibrant colors and dynamic composition. Format: ${format}. This is a placeholder - Vertex AI generation is not yet fully configured.`;

    return {
      url: placeholderUrl,
      metadata: {
        prompt,
        format,
        description: mockDescription,
        width,
        height,
        mimeType: 'image/png',
        note: 'Placeholder fallback - Vertex AI not configured'
      }
    };
  }

  /**
   * Fallback placeholder video generator
   */
  _generatePlaceholderVideo(prompt, format) {
    console.log('[VertexAI] Using placeholder fallback for video');

    const width = this._getWidth(format);
    const height = this._getHeight(format);

    const placeholderUrl = `https://placehold.co/${width}x${height}/e8710a/white?text=${encodeURIComponent('▶ ' + prompt.substring(0, 50))}`;

    const mockStoryboard = `Generated video: ${prompt}. A cinematic sequence with smooth transitions and engaging visual storytelling. Format: ${format}. This is a placeholder - Vertex AI generation is not yet fully configured.`;

    return {
      url: placeholderUrl,
      metadata: {
        prompt,
        format,
        storyboard: mockStoryboard,
        width,
        height,
        mimeType: 'video/mp4',
        note: 'Placeholder fallback - Vertex AI not configured'
      }
    };
  }

  _getWidth(format) {
    const formats = {
      '16:9': 1920,
      '9:16': 1080,
      '1:1': 1024,
      '4:3': 1024,
      '3:4': 768
    };
    return formats[format] || 1024;
  }

  _getHeight(format) {
    const formats = {
      '16:9': 1080,
      '9:16': 1920,
      '1:1': 1024,
      '4:3': 768,
      '3:4': 1024
    };
    return formats[format] || 1024;
  }
}

module.exports = GeminiClient;
