/**
 * Import Prompt Endpoint for MCP Bridge
 * Receives prompts from YTM Agent Collective
 * Generated by Marco (Backend Specialist)
 */

const functions = require('firebase-functions');

/**
 * HTTP endpoint to receive prompts from external sources (MCP Bridge)
 * This is an onRequest handler to allow CORS and cross-origin access
 */
async function importPrompt(req, res) {
  // Enable CORS for cross-origin requests from Agent Collective
  res.set('Access-Control-Allow-Origin', '*');
  res.set('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.set('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  // Handle preflight OPTIONS request
  if (req.method === 'OPTIONS') {
    res.status(204).send('');
    return;
  }

  // Only accept POST requests
  if (req.method !== 'POST') {
    res.status(405).json({
      success: false,
      error: 'Method not allowed. Use POST.'
    });
    return;
  }

  try {
    const { prompt, source, metadata } = req.body;

    // Validate required fields
    if (!prompt || typeof prompt !== 'string') {
      res.status(400).json({
        success: false,
        error: 'Missing or invalid prompt field'
      });
      return;
    }

    if (prompt.trim().length === 0) {
      res.status(400).json({
        success: false,
        error: 'Prompt cannot be empty'
      });
      return;
    }

    // Encode the prompt for URL safety
    const encodedPrompt = encodeURIComponent(prompt.trim());

    // Build the redirect URL to Creative Generator
    // Using the deployed Firebase Hosting URL
    const generatorBaseUrl = 'https://v3-creative-engine.web.app';
    const redirectUrl = `${generatorBaseUrl}?prompt=${encodedPrompt}`;

    // Log the import for monitoring
    console.log('[MCP Bridge] Prompt imported:', {
      source: source || 'unknown',
      promptLength: prompt.length,
      metadata: metadata || {},
      timestamp: new Date().toISOString()
    });

    // Return success with the redirect URL
    res.status(200).json({
      success: true,
      message: 'Prompt received successfully',
      redirectUrl: redirectUrl,
      promptPreview: prompt.substring(0, 100) + (prompt.length > 100 ? '...' : ''),
      timestamp: new Date().toISOString()
    });

  } catch (error) {
    console.error('[MCP Bridge] Error importing prompt:', error);
    res.status(500).json({
      success: false,
      error: 'Internal server error',
      details: error.message
    });
  }
}

module.exports = { importPrompt };
