/**
 * Job Processor for V3 Creative Engine
 * Generated by Marco (Backend Specialist)
 */

const admin = require('firebase-admin');
const GeminiClient = require('../general-context/gemini');

async function processJob(snap, context) {
  const jobId = context.params.jobId;
  const job = snap.data();

  console.log(`[JobProcessor] Processing job ${jobId}`);

  const db = admin.firestore();
  const jobRef = db.collection('jobs').doc(jobId);

  try {
    await jobRef.update({
      status: 'processing',
      updatedAt: admin.firestore.FieldValue.serverTimestamp()
    });

    // Get configuration from environment
    const apiKey = process.env.GEMINI_API_KEY;
    const projectId = process.env.GCP_PROJECT_ID || 'v3-creative-engine';
    const location = process.env.VERTEX_AI_LOCATION || 'us-central1';

    const gemini = new GeminiClient(apiKey, projectId, location);

    const startTime = Date.now();
    let result;

    if (job.type === 'reference_character') {
      // Reference Character Generation
      console.log(`[JobProcessor] Generating reference character: ${job.name}`);

      // Generate the character image
      result = await gemini.generateImage(job.prompt, job.aspectRatio || '9:16');

      // Upload image to Cloud Storage
      if (result.data) {
        console.log(`[JobProcessor] Uploading reference character to Cloud Storage for job ${jobId}`);
        const storageUrl = await uploadImageToStorage(jobId, result.data);
        result.url = storageUrl;
        delete result.data; // Remove base64 data from result
      }

      const processingTimeMs = Date.now() - startTime;

      // Save to reference_characters collection
      const characterRef = await db.collection('reference_characters').add({
        name: job.name,
        type: job.characterType || 'person',
        prompt: job.prompt,
        imageUrl: result.url,
        aspectRatio: job.aspectRatio || '9:16',
        country: job.country || 'korea',
        createdAt: Date.now(),
        createdFrom: 'creative-generator',
        metadata: result.metadata
      });

      console.log(`[JobProcessor] Reference character saved: ${characterRef.id}`);

      // Update job status
      await jobRef.update({
        status: 'complete',
        result: {
          url: result.url,
          characterId: characterRef.id,
          metadata: result.metadata
        },
        processedAt: admin.firestore.FieldValue.serverTimestamp(),
        processingTimeMs,
        updatedAt: admin.firestore.FieldValue.serverTimestamp()
      });

      console.log(`[JobProcessor] Reference character job ${jobId} completed in ${processingTimeMs}ms`);

    } else if (job.type === 'image') {
      // Check if this is an expand job with reference image
      const referenceImageUrl = job.context?.referenceImageUrl || null;
      const expandMode = job.context?.expandMode || false;
      const referenceCharacters = job.referenceCharacters || [];

      if (referenceImageUrl && expandMode) {
        console.log(`[JobProcessor] EXPAND MODE - Using reference image: ${referenceImageUrl}`);
        result = await gemini.generateImage(job.prompt, job.format || '1:1', referenceImageUrl, { expandMode: true });
      } else if (referenceCharacters.length > 0) {
        console.log(`[JobProcessor] Using ${referenceCharacters.length} reference character(s)`);
        // Build reference images array for Nano Banana Pro
        const referenceImages = referenceCharacters.map(char => ({
          url: char.imageUrl,
          type: char.type || 'subject'  // 'subject' or 'style'
        }));
        result = await gemini.generateImage(job.prompt, job.format || '1:1', null, { referenceImages });
      } else {
        result = await gemini.generateImage(job.prompt, job.format || '1:1');
      }

      // Upload actual image data to Cloud Storage if available
      if (result.data) {
        console.log(`[JobProcessor] Uploading image to Cloud Storage for job ${jobId}`);
        const storageUrl = await uploadImageToStorage(jobId, result.data);
        result.url = storageUrl;
        delete result.data; // Remove base64 data from result
      }

      const processingTimeMs = Date.now() - startTime;

      await jobRef.update({
        status: 'complete',
        result: { url: result.url, metadata: result.metadata },
        processedAt: admin.firestore.FieldValue.serverTimestamp(),
        processingTimeMs,
        updatedAt: admin.firestore.FieldValue.serverTimestamp()
      });

      console.log(`[JobProcessor] Job ${jobId} completed in ${processingTimeMs}ms`);

    } else {
      // VIDEO: May be synchronous or asynchronous depending on API
      // Pass sourceImageUrl for image-to-video, or null for text-to-video
      result = await gemini.generateVideo(job.prompt, job.format || '16:9', job.sourceImageUrl || null);

      const processingTimeMs = Date.now() - startTime;

      if (result.data) {
        // Synchronous response - video ready immediately!
        console.log(`[JobProcessor] Video generated synchronously!`);

        const storageUrl = await uploadVideoToStorage(jobId, result.data);

        await jobRef.update({
          status: 'complete',
          result: {
            url: storageUrl,
            metadata: result.metadata
          },
          processedAt: admin.firestore.FieldValue.serverTimestamp(),
          processingTimeMs,
          updatedAt: admin.firestore.FieldValue.serverTimestamp()
        });

        console.log(`[JobProcessor] Job ${jobId} completed synchronously in ${processingTimeMs}ms`);

      } else if (result.operationId) {
        // Async operation - needs polling
        await jobRef.update({
          status: 'generating',
          operationId: result.operationId,
          result: {
            metadata: result.metadata,
            estimatedMinutes: '3-5',
            message: 'Video generation in progress...'
          },
          startedAt: admin.firestore.FieldValue.serverTimestamp(),
          processingTimeMs,
          updatedAt: admin.firestore.FieldValue.serverTimestamp()
        });

        console.log(`[JobProcessor] Video operation started: ${result.operationId}`);
        console.log(`[JobProcessor] Job ${jobId} will be polled for completion`);
      } else {
        throw new Error('Unexpected video generation response format');
      }
    }

  } catch (error) {
    console.error(`[JobProcessor] Job ${jobId} failed:`, error);
    await jobRef.update({
      status: 'error',
      error: error.message,
      updatedAt: admin.firestore.FieldValue.serverTimestamp()
    });
    throw error;
  }
}

/**
 * Upload video to Cloud Storage
 * @param {string} jobId - Job ID
 * @param {string} base64Data - Base64 encoded video data
 * @returns {string} Public URL of uploaded video
 */
async function uploadVideoToStorage(jobId, base64Data) {
  const bucket = admin.storage().bucket();
  const fileName = `videos/${jobId}.mp4`;
  const file = bucket.file(fileName);

  // Convert base64 to buffer
  const buffer = Buffer.from(base64Data, 'base64');

  console.log(`[JobProcessor] Uploading video: ${fileName} (${buffer.length} bytes)`);

  await file.save(buffer, {
    metadata: {
      contentType: 'video/mp4',
      metadata: {
        jobId: jobId,
        generatedAt: new Date().toISOString()
      }
    },
    public: true,
    validation: false
  });

  const publicUrl = `https://storage.googleapis.com/${bucket.name}/${fileName}`;
  console.log(`[JobProcessor] Video uploaded: ${publicUrl}`);

  return publicUrl;
}

/**
 * Upload image to Cloud Storage
 * @param {string} jobId - Job ID
 * @param {string} base64Data - Base64 encoded image data
 * @returns {string} Public URL of uploaded image
 */
async function uploadImageToStorage(jobId, base64Data) {
  const bucket = admin.storage().bucket();
  const fileName = `images/${jobId}.png`;
  const file = bucket.file(fileName);

  // Convert base64 to buffer
  const buffer = Buffer.from(base64Data, 'base64');

  console.log(`[JobProcessor] Uploading image: ${fileName} (${buffer.length} bytes)`);

  await file.save(buffer, {
    metadata: {
      contentType: 'image/png',
      metadata: {
        jobId: jobId,
        generatedAt: new Date().toISOString()
      }
    },
    public: true,
    resumable: false // Faster for small files
  });

  // Get public URL
  const publicUrl = `https://storage.googleapis.com/${bucket.name}/${fileName}`;

  console.log(`[JobProcessor] Image uploaded: ${publicUrl}`);

  return publicUrl;
}

/**
 * Upload video to Cloud Storage
 * @param {string} jobId - Job ID
 * @param {string} base64Data - Base64 encoded video data
 * @returns {string} Public URL of uploaded video
 */
async function uploadVideoToStorage(jobId, base64Data) {
  const bucket = admin.storage().bucket();
  const fileName = `videos/${jobId}.mp4`;
  const file = bucket.file(fileName);

  // Convert base64 to buffer
  const buffer = Buffer.from(base64Data, 'base64');

  console.log(`[JobProcessor] Uploading video: ${fileName} (${buffer.length} bytes)`);

  await file.save(buffer, {
    metadata: {
      contentType: 'video/mp4',
      metadata: {
        jobId: jobId,
        generatedAt: new Date().toISOString()
      }
    },
    public: true,
    resumable: false
  });

  // Get public URL
  const publicUrl = `https://storage.googleapis.com/${bucket.name}/${fileName}`;

  console.log(`[JobProcessor] Video uploaded: ${publicUrl}`);

  return publicUrl;
}

module.exports = { processJob };
