#!/bin/bash

# Template Stamper - Daily Backup Script
# Runs at 10pm daily to backup progress and discussions
#
# This script:
# 1. Creates a daily progress log with timestamp
# 2. Commits any changes to git
# 3. Pushes to remote repository

set -e  # Exit on error

REPO_DIR="/Users/ivs/template-stamper"
DATE=$(date +"%Y-%m-%d")
TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
PROGRESS_FILE="$REPO_DIR/docs/progress/daily-log-$DATE.md"

echo "=== Template Stamper Daily Backup ==="
echo "Date: $TIMESTAMP"
echo "Repository: $REPO_DIR"

cd "$REPO_DIR"

# Check if there are any changes
if [[ -z $(git status --porcelain) ]]; then
    echo "No changes to backup today."
    exit 0
fi

# Create daily progress log if it doesn't exist
if [ ! -f "$PROGRESS_FILE" ]; then
    cat > "$PROGRESS_FILE" << EOF
# Daily Progress Log - $DATE

**Date:** $DATE
**Generated:** $TIMESTAMP

---

## Changes Made Today

$(git status --short)

---

## Files Modified

\`\`\`
$(git diff --name-only)
\`\`\`

---

## Commit Summary

This daily backup captures the state of the project at 10pm.

EOF
fi

# Stage all changes
echo "Staging changes..."
git add .

# Create commit message
COMMIT_MSG="Daily backup: $DATE

Automated backup at 10pm
- Progress logged to docs/progress/daily-log-$DATE.md
- All changes from today's work captured

Generated by daily-backup.sh"

# Commit changes
echo "Committing changes..."
git commit -m "$COMMIT_MSG" || {
    echo "No changes to commit (possibly already committed)"
    exit 0
}

# Push to remote
echo "Pushing to remote..."
git push origin main || {
    echo "Warning: Failed to push to remote. Will retry on next run."
    exit 1
}

echo "✅ Backup completed successfully!"
echo "Log saved to: $PROGRESS_FILE"
